spring:
  datasource:
    url: jdbc:h2:mem:mydb;DB_CLOSE_ON_EXIT=FALSE
    username: sa
    password: password
    driverClassName: org.h2.Driver
  jpa:
    spring.jpa.database-platform: org.hibernate.dialect.H2Dialect
    defer-datasource-initialization: true
    properties:
      hibernate:
        show_sql: false
        format_sql: false
  h2:
    console.enabled: true    
    console.path: /h2-console
    console.settings.trace: false 
    spring.h2.console.settings.web-allow-others: false
